# cloudbuild.yaml
# This file defines the steps for Cloud Build to build and deploy your Cloud Run service.

steps:
  # Step 1: Pull the previous 'latest' image for Docker layer caching.
  # This step attempts to pull the last built image from Artifact Registry.
  # The '|| exit 0' ensures the build doesn't fail if the image doesn't exist yet (e.g., first build).
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull previous image for cache'
    entrypoint: /bin/bash
    args:
      - '-c'
      - >-
        docker pull ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest
        || exit 0

  # Step 2: Build the Docker image for your backend service.
  # This step uses the 'docker' builder to build an image from your backend/Dockerfile.
  # It uses '--cache-from' to leverage layers from the previously pulled image, speeding up subsequent builds.
  # The image is tagged with the commit SHA and 'latest' for Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '--cache-from'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'backend/Dockerfile' # Explicitly specify Dockerfile path if not named 'Dockerfile' or not in context root
      - './backend' # Path to your Dockerfile and application context
      
  # Step 3: Push the newly built Docker images to Artifact Registry.
  # This pushes both the commit SHA tagged image and the 'latest' tagged image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - '--all-tags' # Pushes all tags associated with the image (COMMIT_SHA and latest)
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}'

  # Step 4: Deploy the built Docker image to Cloud Run.
  # This step uses the 'gcloud' builder to deploy the image with all specified configurations.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # Cloud Run service name (from trigger substitution)
      - '--image'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}' # Use the image built in the previous step
      - '--region'
      - '${_DEPLOY_REGION}' # Cloud Run region (from trigger substitution)
      - '--platform=managed'
      - '--service-account=${_SA_EMAIL}' # Service account for the Cloud Run service
      - '--set-env-vars=NODE_ENV=production,STORAGE_PROVIDER=gcp,GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},CORS_ORIGIN=${_CORS_ORIGIN}'
      - '--set-secrets=JWT_SECRET=jwt-secret:latest'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--quiet' # Suppress interactive prompts

# This 'images' section tells Cloud Build to automatically push these tagged images
# to Artifact Registry after the build completes. It's a convenient shortcut
# for the 'docker push' step, but having the explicit 'Push Docker Image' step
# gives you more control and is often preferred for clarity and custom tagging.
# If you use the explicit 'Push Docker Image' step (Step 3 above), you can remove this 'images' block.
# images:
#   - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
#   - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:latest'

# Substitutions:
# These variables are defined in the Cloud Build trigger settings and passed into the build.
# You MUST define these in your Cloud Build trigger configuration in the Google Cloud Console.
substitutions:
  _SERVICE_NAME: 'toast-stats-git' # e.g., 'my-backend-api'
  _DEPLOY_REGION: 'us-east1' # e.g., 'us-central1', 'europe-west1'
  _SA_EMAIL: 'toast-stats-backend@artful-bonito-485102-i9.iam.gserviceaccount.com' # e.g., 'my-cloud-run-sa@my-project.iam.gserviceaccount.com'
  _GCS_BUCKET_NAME: 'toast-stats-raw-csv-artful-bonito-485102-i9' # e.g., 'my-app-data-bucket'
  _CORS_ORIGIN: 'https://ts-taverns.red' # e.g., 'https://my-firebase-app.web.app'
  _AR_HOSTNAME: 'us-east1-docker.pkg.dev' # Hostname for your Artifact Registry repository (e.g., us-central1-docker.pkg.dev)
  _AR_PROJECT_ID: 'artful-bonito-485102-i9' # Your GCP Project ID (can also use built-in PROJECT_ID)
  _AR_REPOSITORY: 'cloud-run-source-deploy' # Name of your Artifact Registry repository (e.g., 'cloud-run-source-deploy')

# Optional: Define timeout for the entire build process
timeout: '1200s' # 20 minutes