import type { DesignToken } from './types'

/**
 * Comprehensive spacing tokens system
 */
export const spacingTokens: DesignToken[] = [
  // Touch target requirements
  {
    name: '--tm-touch-target',
    value: '44px',
    category: 'spacing',
    description: 'Minimum touch target size (accessibility requirement)',
    usage: ['interactive-elements', 'buttons', 'links'],
  },
  {
    name: '--tm-touch-target-min',
    value: '44px',
    category: 'spacing',
    description: 'Minimum touch target size alias',
    usage: ['interactive-elements', 'buttons', 'links'],
  },

  // Base spacing scale (comprehensive)
  {
    name: '--tm-space-0',
    value: '0px',
    category: 'spacing',
    description: 'Zero spacing',
    usage: ['reset-margins', 'reset-padding'],
  },
  {
    name: '--tm-space-px',
    value: '1px',
    category: 'spacing',
    description: 'Single pixel spacing',
    usage: ['borders', 'fine-adjustments'],
  },
  {
    name: '--tm-space-0-5',
    value: '2px',
    category: 'spacing',
    description: 'Half unit spacing',
    usage: ['fine-spacing', 'micro-adjustments'],
  },
  {
    name: '--tm-space-1',
    value: '4px',
    category: 'spacing',
    description: 'Base unit spacing',
    usage: ['tight-spacing', 'icon-gaps'],
  },
  {
    name: '--tm-space-1-5',
    value: '6px',
    category: 'spacing',
    description: 'One and half unit spacing',
    usage: ['small-gaps', 'fine-padding'],
  },
  {
    name: '--tm-space-2',
    value: '8px',
    category: 'spacing',
    description: 'Double unit spacing',
    usage: ['component-padding', 'element-gaps'],
  },
  {
    name: '--tm-space-2-5',
    value: '10px',
    category: 'spacing',
    description: 'Two and half unit spacing',
    usage: ['small-padding', 'list-gaps'],
  },
  {
    name: '--tm-space-3',
    value: '12px',
    category: 'spacing',
    description: 'Triple unit spacing',
    usage: ['button-padding', 'form-spacing'],
  },
  {
    name: '--tm-space-3-5',
    value: '14px',
    category: 'spacing',
    description: 'Three and half unit spacing',
    usage: ['medium-padding', 'text-spacing'],
  },
  {
    name: '--tm-space-4',
    value: '16px',
    category: 'spacing',
    description: 'Quad unit spacing',
    usage: ['section-padding', 'card-padding'],
  },
  {
    name: '--tm-space-5',
    value: '20px',
    category: 'spacing',
    description: 'Five unit spacing',
    usage: ['component-margins', 'section-gaps'],
  },
  {
    name: '--tm-space-6',
    value: '24px',
    category: 'spacing',
    description: 'Six unit spacing',
    usage: ['section-margins', 'component-separation'],
  },
  {
    name: '--tm-space-8',
    value: '32px',
    category: 'spacing',
    description: 'Eight unit spacing',
    usage: ['page-margins', 'major-sections'],
  },
  {
    name: '--tm-space-10',
    value: '40px',
    category: 'spacing',
    description: 'Ten unit spacing',
    usage: ['large-margins', 'section-separation'],
  },
  {
    name: '--tm-space-12',
    value: '48px',
    category: 'spacing',
    description: 'Twelve unit spacing',
    usage: ['page-sections', 'major-components'],
  },
  {
    name: '--tm-space-16',
    value: '64px',
    category: 'spacing',
    description: 'Sixteen unit spacing',
    usage: ['page-layout', 'hero-sections'],
  },
  {
    name: '--tm-space-20',
    value: '80px',
    category: 'spacing',
    description: 'Twenty unit spacing',
    usage: ['large-sections', 'page-breaks'],
  },
  {
    name: '--tm-space-24',
    value: '96px',
    category: 'spacing',
    description: 'Twenty-four unit spacing',
    usage: ['major-sections', 'page-divisions'],
  },

  // Semantic spacing aliases
  {
    name: '--tm-space-xs',
    value: 'var(--tm-space-1)',
    category: 'spacing',
    description: 'Extra small semantic spacing (4px)',
    usage: ['tight-spacing', 'icon-gaps'],
  },
  {
    name: '--tm-space-sm',
    value: 'var(--tm-space-2)',
    category: 'spacing',
    description: 'Small semantic spacing (8px)',
    usage: ['component-padding', 'element-gaps'],
  },
  {
    name: '--tm-space-md',
    value: 'var(--tm-space-4)',
    category: 'spacing',
    description: 'Medium semantic spacing (16px)',
    usage: ['section-padding', 'card-padding'],
  },
  {
    name: '--tm-space-lg',
    value: 'var(--tm-space-6)',
    category: 'spacing',
    description: 'Large semantic spacing (24px)',
    usage: ['section-margins', 'component-separation'],
  },
  {
    name: '--tm-space-xl',
    value: 'var(--tm-space-8)',
    category: 'spacing',
    description: 'Extra large semantic spacing (32px)',
    usage: ['page-margins', 'major-sections'],
  },
  {
    name: '--tm-space-2xl',
    value: 'var(--tm-space-12)',
    category: 'spacing',
    description: 'Double extra large semantic spacing (48px)',
    usage: ['page-sections', 'major-components'],
  },
  {
    name: '--tm-space-3xl',
    value: 'var(--tm-space-16)',
    category: 'spacing',
    description: 'Triple extra large semantic spacing (64px)',
    usage: ['page-layout', 'hero-sections'],
  },

  // Component-specific spacing
  {
    name: '--tm-component-padding-xs',
    value: 'var(--tm-space-2)',
    category: 'spacing',
    description: 'Extra small component padding (8px)',
    usage: ['small-buttons', 'compact-forms'],
  },
  {
    name: '--tm-component-padding-sm',
    value: 'var(--tm-space-3)',
    category: 'spacing',
    description: 'Small component padding (12px)',
    usage: ['buttons', 'form-inputs'],
  },
  {
    name: '--tm-component-padding-md',
    value: 'var(--tm-space-4)',
    category: 'spacing',
    description: 'Medium component padding (16px)',
    usage: ['cards', 'panels'],
  },
  {
    name: '--tm-component-padding-lg',
    value: 'var(--tm-space-6)',
    category: 'spacing',
    description: 'Large component padding (24px)',
    usage: ['large-cards', 'sections'],
  },
  {
    name: '--tm-component-padding-xl',
    value: 'var(--tm-space-8)',
    category: 'spacing',
    description: 'Extra large component padding (32px)',
    usage: ['hero-sections', 'major-components'],
  },

  // Component margins
  {
    name: '--tm-component-margin-xs',
    value: 'var(--tm-space-2)',
    category: 'spacing',
    description: 'Extra small component margin (8px)',
    usage: ['tight-layouts', 'compact-spacing'],
  },
  {
    name: '--tm-component-margin-sm',
    value: 'var(--tm-space-4)',
    category: 'spacing',
    description: 'Small component margin (16px)',
    usage: ['component-spacing', 'element-separation'],
  },
  {
    name: '--tm-component-margin-md',
    value: 'var(--tm-space-6)',
    category: 'spacing',
    description: 'Medium component margin (24px)',
    usage: ['section-spacing', 'component-separation'],
  },
  {
    name: '--tm-component-margin-lg',
    value: 'var(--tm-space-8)',
    category: 'spacing',
    description: 'Large component margin (32px)',
    usage: ['major-spacing', 'section-separation'],
  },
  {
    name: '--tm-component-margin-xl',
    value: 'var(--tm-space-12)',
    category: 'spacing',
    description: 'Extra large component margin (48px)',
    usage: ['page-sections', 'major-divisions'],
  },
]
