/**
 * Time-series data types for district metrics over time.
 * File location: time-series/district_{id}/{programYear}.json
 *
 * These types define the structure for time-series index files that store
 * aggregated metrics for districts across snapshots. The data is partitioned
 * by program year (July 1 - June 30) for efficient querying.
 *
 * @module time-series
 * @see Requirements 13.1, 13.2, 13.3
 */

/**
 * Club health counts breakdown.
 * Categorizes clubs by their health status.
 */
export interface ClubHealthCounts {
  /** Total number of clubs */
  total: number
  /** Number of thriving clubs */
  thriving: number
  /** Number of vulnerable clubs */
  vulnerable: number
  /** Number of clubs requiring intervention */
  interventionRequired: number
}

/**
 * A single data point in the time-series index.
 * Contains aggregated metrics for a snapshot date.
 *
 * This structure is generated by collector-cli during the compute-analytics
 * pipeline and read by the backend TimeSeriesIndexService.
 *
 * @see Requirements 13.1
 */
export interface TimeSeriesDataPoint {
  /** Date of the snapshot in YYYY-MM-DD format */
  date: string
  /** Unique identifier for the snapshot */
  snapshotId: string
  /** Total membership count across all clubs */
  membership: number
  /** Total payments received */
  payments: number
  /** Total DCP goals achieved */
  dcpGoals: number
  /** Total number of distinguished clubs */
  distinguishedTotal: number
  /** Club health counts breakdown */
  clubCounts: ClubHealthCounts
}

/**
 * Summary statistics for a program year.
 * Pre-computed by collector-cli during the compute-analytics pipeline.
 *
 * These statistics provide quick access to key metrics without
 * needing to iterate through all data points.
 *
 * @see Requirements 13.2
 */
export interface ProgramYearSummary {
  /** Total number of data points in the program year */
  totalDataPoints: number
  /** Membership count at the start of the program year */
  membershipStart: number
  /** Membership count at the end of the program year */
  membershipEnd: number
  /** Peak membership count during the program year */
  membershipPeak: number
  /** Lowest membership count during the program year */
  membershipLow: number
}

/**
 * Program year index file structure.
 * Partitioned by program year (July 1 - June 30).
 *
 * Each district has one file per program year containing all
 * time-series data points for that period.
 *
 * File location: time-series/district_{id}/{programYear}.json
 * Example: time-series/district_42/2023-2024.json
 *
 * @see Requirements 13.2
 */
export interface ProgramYearIndexFile {
  /** District identifier (e.g., "42", "F") */
  districtId: string
  /** Program year identifier (e.g., "2023-2024") */
  programYear: string
  /** Start date of the program year (e.g., "2023-07-01") */
  startDate: string
  /** End date of the program year (e.g., "2024-06-30") */
  endDate: string
  /** ISO timestamp when the index was last updated */
  lastUpdated: string
  /** Array of time-series data points for this program year */
  dataPoints: TimeSeriesDataPoint[]
  /** Pre-computed summary statistics for this program year */
  summary: ProgramYearSummary
}

/**
 * Metadata for a district's time-series indexes.
 * Provides an overview of available data for a district.
 *
 * File location: time-series/district_{id}/index-metadata.json
 *
 * @see Requirements 13.3
 */
export interface TimeSeriesIndexMetadata {
  /** District identifier (e.g., "42", "F") */
  districtId: string
  /** ISO timestamp when the metadata was last updated */
  lastUpdated: string
  /** List of available program years (e.g., ["2022-2023", "2023-2024"]) */
  availableProgramYears: string[]
  /** Total number of data points across all program years */
  totalDataPoints: number
}
